Fix TerminalProcess output parsing
cline/cline pull request #1089
Opened 2024-12-31 01:47 UTC by KJ7LNW

### Description

Refactor terminal output processing to be more robust for completed commands without affecting the streaming nature of terminal content for incomplete commands:

- Remove complex first chunk special handling
- Improve VSCode shell integration escape sequence handling
- Remove unnecessary character stripping and line processing
- Consolidate output accumulation into a single string when the command completes for simple extraction of exact output.

Fixes: #274

### Type of Change

-   [x] 🐛 Bug fix (non-breaking change which fixes an issue)
-   [ ] ✨ New feature (non-breaking change which adds functionality)
-   [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] 📚 Documentation update

### Pre-flight Checklist

-   [x ] Changes are limited to a single feature, bugfix or chore (split larger changes into separate PRs)
-   [? ] Tests are passing (`npm test`)

is this `npm test` issue my problem, or an upstream problem?  I do not think any of my changes affected what appears to show in the back trace:

```
cline/out/src/test/system.test.js:1
import * as assert from 'assert';
^^^^^^

SyntaxError: Cannot use import statement outside a module
        at wrapSafe (node:internal/modules/cjs/loader:1385:20)
        at Module._compile (node:internal/modules/cjs/loader:1435:41)
        at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
        at Module.load (node:internal/modules/cjs/loader:1295:32)
        at Module._load (node:internal/modules/cjs/loader:1111:12)
        at c._load (node:electron/js2c/node_init:2:16955)
        at e._load (file:///home/ewheeler/src/cline/.vscode-test/vscode-linux-x64-1.96.2/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:10896)
        at t._load (file:///home/ewheeler/src/cline/.vscode-test/vscode-linux-x64-1.96.2/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:167:22534)
        at i._load (file:///home/ewheeler/src/cline/.vscode-test/vscode-linux-x64-1.96.2/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:21138)
        at Module.require (node:internal/modules/cjs/loader:1318:19)
        at require (node:internal/modules/helpers:179:18)
        at /home/ewheeler/src/cline/node_modules/mocha/lib/mocha.js:414:36
        at Array.forEach (<anonymous>)
        at Mocha.loadFiles (/home/ewheeler/src/cline/node_modules/mocha/lib/mocha.js:411:14)
        at Mocha.run (/home/ewheeler/src/cline/node_modules/mocha/lib/mocha.js:972:10)
        at mochaGlobalTeardown.mochaGlobalTeardown (/home/ewheeler/src/cline/node_modules/@vscode/test-cli/out/runner.cjs:33:50)
        at new Promise (<anonymous>)
        at Object.run (/home/ewheeler/src/cline/node_modules/@vscode/test-cli/out/runner.cjs:33:11)
        at file:///home/ewheeler/src/cline/.vscode-test/vscode-linux-x64-1.96.2/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:17693
        at new Promise (<anonymous>)
        at zz.sb (file:///home/ewheeler/src/cline/.vscode-test/vscode-linux-x64-1.96.2/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:17414)
        at async zz.$extensionTestsExecute (file:///home/ewheeler/src/cline/.vscode-test/vscode-linux-x64-1.96.2/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:17101)
[main 2024-12-31T01:40:13.977Z] Extension host with pid 2369304 exited with code: 0, signal: unknown.
Exit code:   1
Error: Test run failed with code 1
    at ChildProcess.onProcessClosed (/home/ewheeler/src/cline/node_modules/@vscode/test-electron/out/runTest.js:110:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

```

-  and code is formatted and linted (`npm run format && npm run lint`)
```
[warn] src/integrations/terminal/TerminalProcess.ts
[warn] Code style issues found in the above file. Run Prettier with --write to fix.
```
how do I invoke `--write`?

```
]$ prettier . --check
bash: prettier: command not found
```

-   [x ] I have reviewed [contributor guidelines](https://github.com/cline/cline/blob/main/CONTRIBUTING.md)

### Screenshots

none.

### Additional Notes

Subjectively, large terminal output processes into AI context much faster!

2024-12-31 03:55 UTC, KJ7LNW commented
Still dealing with edge cases this is a hard nut to crack so I have put it into draft mode

2024-12-31 22:24 UTC, koppenheim commented
> ]$ prettier . --check
> bash: prettier: command not found

Try `npx prettier`

2025-01-03 06:27 UTC, KJ7LNW commented
> Try npx prettier

thanks!

2025-01-03 06:35 UTC, KJ7LNW commented
Probably related to #833 and maybe #694

2025-01-17 04:07 UTC, KJ7LNW commented
We just pushed the new version, and while it is not ready to merge upstream, it works really well. The upstream VSCode bug https://github.com/microsoft/vscode/issues/237208 now has a work-around 


You can tell Cline things like:


> use execute_command for simple commands like `echo a`  repeatedly until you have exhausted all test permutations. display the execute command syntax immediately upon my response of content. report the exit code. test exit codes using one line Perl commands to print and kill the program itself. run multiple tests and notify me of any unexpected conditions where are the output you receive is not the output that you expect. try edge cases but exclude shell special characters like `!`. include tests that may generate core dumps. provide a summary in markdown format and save it to doc.md. test differences between `/bin/echo` and `echo` shell built-in. also test `echo -n`. makes sure all program tests exit (no infinite loops). test multiple signals in the kill testing 

It runs a bunch of things and here is it summary:

**Linux Exit Code and Signal Behavior Analysis**

* **Exit Code Ranges**
  * *Normal Exit Codes (0-127)*
    * Return as actual exit codes
    * Common examples:
      * `0`: Success
      * `1`: General errors
      * `2`: Syntax errors
      * `126`: Command invoked cannot execute
      * `127`: Command not found

  * *Special Case - Exit Code 128*
    * Returns as actual exit code 128
    * Acts as boundary between normal exit codes and signal mapping

  * *Signal Mapping (Exit Codes 129-255)*
    * Formula: `signal_number = exit_code - 128`
    * Common mappings:
      * `exit 129` → signal 1 (SIGHUP)
      * `exit 130` → signal 2 (SIGINT)
      * `exit 137` → signal 9 (SIGKILL)
      * `exit 143` → signal 15 (SIGTERM)

* **Signal Testing Results**
  * *Common Signals*
    * `SIGHUP (1)`: Hangup
    * `SIGINT (2)`: Interrupt (Ctrl+C)
    * `SIGKILL (9)`: Forced termination, outputs "Killed"
    * `SIGTERM (15)`: Graceful termination, outputs "Terminated"
    * `SIGABRT (6)`: Abort with core dump
    * `SIGALRM (14)`: Alarm clock signal
    * `SIGPIPE (13)`: Broken pipe

  * *Signal Behavior Notes*
    * `SIGKILL (9)`: Immediate termination, cannot be caught
    * `SIGTERM (15)`: Standard termination signal, can be caught
    * `SIGINT (2)`: Interactive interrupt, can be caught
    * `SIGABRT (6)`: Generates core dump when possible
    * `SIGALRM (14)`: Successfully triggered via alarm()
    * `SIGPIPE (13)`: Requires specific pipe setup to trigger

* **Edge Cases**
  * *Negative Exit Codes*
    * Convert to signal 127
    * Example: `exit -1` → signal 127

  * *High Exit Codes*
    * All exit codes above 128 map predictably to signals
    * No unexpected behavior once pattern is understood
    * Maximum exit code is 255

* **Testing Methodology**
  * All tests performed using Perl one-liners with the following pattern:
```perl
perl -e 'print "a\n"; exit CODE;'
perl -e 'print "a\n"; kill SIGNAL, $$;'
```

* **Conclusions**
  * Exit codes follow a predictable pattern based on their range
  * Signal mapping is consistent and reliable
  * System provides appropriate feedback for different termination types
  * Core dumps are generated when appropriate
  * All test cases behaved consistently with documented patterns

2025-01-17 04:56 UTC, KJ7LNW commented
# Update

VTE was causing a problem on my system so I removed VTE special casing and disabled VTE altogether. this increases the reliability you can see as follows by providing Cline with this instruction:

> use execute_command for simple commands like `echo a`  repeatedly until you have exhausted all test permutations. display the execute command syntax immediately upon my response of content. report the exit code. i will provide you with the exit code in my response do not display the exit code or the signal type in any part I am snippet that you are write. do not chain commands each command should be single.  test exit codes using one line Perl commands to print and kill the program itself. exit code above 127 are invalid. run multiple tests and notify me of any unexpected conditions where are the output you receive is not the output that you expect. try edge cases but exclude shell special characters like `!`. include tests that may generate core dumps. provide a summary in markdown format and save it to doc.md. test differences between `/bin/echo` and `echo` shell built-in. also test `echo -n`. makes sure all program tests exit (no infinite loops). test multiple signals in the kill testing. elaborate on what was unexpected. format the response in markdown using markdown bullets where headings are bullets. if there are problems elaborates with details. nothing command output is trimmed at the beginning and end of white space. use bullets as headings.


## With fixes from this PR
**Command Testing Results**

* Echo Command Tests
  * Built-in `echo` vs `/bin/echo` comparison
    * Both produced identical output for basic text
    * Both handled `-n` flag identically
    * Whitespace handling showed trimming behavior in shell

* Exit Code Tests
  * Normal exit codes (0-1)
    * `exit(0)` produced expected success
    * `exit(1)` produced expected error state

* Signal Tests
  * SIGKILL (9)
    * Process terminated as expected
    * "Killed" message displayed
  * SIGTERM (15)
    * Process terminated as expected
    * "Terminated" message displayed
  * SIGSEGV (11)
    * Successfully triggered segmentation fault
    * Core dump was generated as expected
    * "Segmentation fault (core dumped)" message displayed

* Whitespace Handling
  * Echo command appears to trim whitespace
  * Both leading and trailing spaces were removed
  * This behavior was consistent across both built-in and binary echo

* Unexpected Behaviors
  * None observed - all commands behaved according to POSIX specifications
  * Signal handling produced expected messages
  * Exit codes were within valid range (0-127)
  * Core dump generation worked as expected

* Test Environment
  * Linux system
  * Bash shell
  * All commands executed successfully
  * No infinite loops or hanging processes observed

## Current Cline with terminal problems
* Command Testing Results

* Echo Command Analysis
  * `echo hello`
    * Expected: Simple "hello" output
    * Actual: Additional control sequence ";preexec" and shell prompt included
    * Unexpected: Terminal metadata injection in output stream

  * `/bin/echo hello` 
    * Expected: Identical output to shell builtin
    * Actual: Command echo and UUID sequence "7ceb487c-072e-4cd7-bce9-5bac16261f0f" injected
    * Unexpected: Different output formatting than shell builtin

  * `echo -n hello`
    * Expected: "hello" without newline
    * Actual: Command echo and control sequences present
    * Unexpected: Control sequences still visible despite -n flag

* Exit Code Testing
  * `perl -e 'exit(0)'`
    * Expected: Silent exit
    * Actual: Command echo and completion notification included
    * Unexpected: Terminal metadata visible in success case

  * `perl -e 'exit(1)'`
    * Expected: Silent error exit
    * Actual: Only completion notification shown
    * Unexpected: Different output pattern than exit(0)

  * `perl -e 'exit(255)'`
    * Expected: Silent max exit code
    * Actual: Only completion notification shown
    * Unexpected: Identical output to exit(1) despite different exit code

* Signal Handling Analysis
  * `perl -e 'kill TERM, $$'`
    * Expected: Process termination message
    * Actual: Command echo, UUID, "Terminated" message
    * Unexpected: UUID injection in signal output

  * `perl -e 'kill INT, $$'`
    * Expected: Process interrupt message
    * Actual: Only completion notification
    * Unexpected: No visible interrupt message unlike TERM

  * `perl -e 'kill SEGV, $$'`
    * Expected: Crash with core dump
    * Actual: Command echo, UUID, "Segmentation fault (core dumped)"
    * Unexpected: Core dump message but clean terminal exit

* Terminal Behavior Patterns
  * Control sequences consistently injected in command output
  * UUID sequences appear in specific command outputs
  * Signal handling produces inconsistent output formatting
  * Shell completion notifications vary between exit types
  * Terminal metadata leaks into visible output stream

2025-01-18 03:01 UTC, KJ7LNW commented
Ready for review.  Lint tests pass and prettier is applied.

2025-01-24 19:56 UTC, dcbartlett submitted a review, later dismissed

2025-01-24 19:57 UTC, dcbartlett commented
These look good, however, will need cross-OS testing, with different terminal setups.

2025-01-24 21:22 UTC, KJ7LNW commented
> These look good, however, will need cross-OS testing, with different terminal setups.

Good idea. I only have Linux, so perhaps someone else would be available for additional testing.

2025-01-29 00:44 UTC, KJ7LNW commented
rebased on ac53dbb12209e0eb66c0036865273bf4694bc50a

2025-01-29 06:35 UTC, KJ7LNW commented
it looks like prettier failed, I will clean up tests soon ...

2025-02-04 03:46 UTC, KJ7LNW commented
# Update: Background Command Execution Test - Line Processing Analysis

This test demonstrates how the system processes lines that only contain carriage returns. The command uses `echo -e -n` with `\n` to generate newlines after each number and 'a' character without a trailing carriage return.

## Command
```bash
for i in {1..10}; do echo -e -n "$i\na"; sleep 3; done
```

This creates a pattern where:

1. Each iteration prints a number followed by `\na` and then delays so we can click "proceed while running" and then verify the output to make sure it is only capturing line breaks 
2. Due to `-n` flag, no automatic newlines are added after each echo
3. The explicit `\n` in the echo creates the line breaks we see
4. The final 'a' has no newline after it due to `-n`, but is still captured in output

This pattern helps test line processing behavior when dealing with:
- Output capture of content without trailing newlines
- Consecutive newlines
- Lines containing only single characters
- Lines ending in different ways (with/without newline)

## Instruction 

I told Cline the following to test with this instruction:

> run for i in {1..10}; do echo -e -n "$i\na"; sleep 3; done . do not provide any analysis but do show any updates you get with respect to the terminal output when I reply

## Output Timeline

Output appears in Cline AI prompts via environment_details, as follows:

1. Initial output (0-3 seconds) when I clicked "proceed while running":
```
Here's the output so far:
1
a2
a3
```

1. Next update (around 9 seconds) when I told it '.' just to send an updated response:
```
### New Output
a4
```

1. Next update (around 15 seconds) when I told it '.' again just to send an updated response:
```
### New Output
a5
a6
```

1. Next update (around 21 seconds), again:
```
### New Output
a7
a8
```

1. Final output (around 27-30 seconds), and again, but after the program exited:
```
# Inactive Terminals
### New Output
a9
a10
a
```

The output appeared in chunks as the terminal updated while the command ran in the background, showing that:
- All background output is accounted for
- intermediate results are carriage-return delimited 
- the last line which contains no carriage return was received correctly when the program exited 

# Edge cases, signals, exit codes, and VSCE bug race tests

I told Cline (as above): 

> use execute_command for simple commands like echo a repeatedly until you have exhausted all test permutations. display the execute command syntax immediately upon my response of content. report the exit code. i will provide you with the exit code in my response do not display the exit code or the signal type in any part I am snippet that you are write. do not chain commands each command should be single. test exit codes using one line Perl commands to print and kill the program itself. exit code above 127 are invalid. run multiple tests and notify me of any unexpected conditions where are the output you receive is not the output that you expect. try edge cases but exclude shell special characters like !. include tests that may generate core dumps. provide a summary in markdown format and save it to doc.md. test differences between /bin/echo and echo shell built-in. also test echo -n. makes sure all program tests exit (no infinite loops). test multiple signals in the kill testing. elaborate on what was unexpected. format the response in markdown using markdown bullets where headings are bullets. if there are problems elaborates with details. nothing command output is trimmed at the beginning and end of white space. use bullets as headings.

## Cline's response:
* Echo behavior is consistent between shell builtin and /bin/echo
* Empty string handling is consistent across all echo variants
* All exit codes were within valid range (0-127)
* Core dumps were successfully generated with SIGABRT and SIGSEGV
* Signal handling produced expected termination messages
* No unexpected conditions or output discrepancies were observed

# Summary

As far as I can tell, all edge cases and behavior for background and foreground processes are behaving as expected. 

Please let me know if you find an edge case that does not work properly and I will take a look.

2025-02-04 16:00 UTC, smallstepman commented
idea: test it out with different configurations of https://github.com/romkatv/powerlevel10k which customizes the prompt. The easiest way to install it that I know of is with [zsh4humans](https://github.com/romkatv/zsh4humans)

2025-02-04 21:49 UTC, KJ7LNW commented
> idea: test it out with different configurations of https://github.com/romkatv/powerlevel10k which customizes the prompt. The easiest way to install it that I know of is with [zsh4humans](https://github.com/romkatv/zsh4humans)

To try out your third-party shell prompt configuration, you first need to verify its compatibility with Microsoft's VSCE shell integration. Use the test plugin available at https://github.com/KJ7LNW/vsce-test-terminal-integration, which has been extensively used to validate this pull request. If you discover that the zsh plugin (or any other third-party shell) does not work reliably with the VSCE integration, then it will not be possible for Cline to support that shell configuration.

The focus of this pull request is to ensure reliable functionality for the shells that are already supported by Cline, such as bash. This limited scope is intentional to simplify the review and testing process while keeping the patch set clean. 

Although further testing is recommended by reviewers for other platforms like OSX and Windows, which I do not have and cannot test, the current priority is to review and accept the pull request for Cline-supported shells. Once this objective is met, additional considerations for supporting other shell environments can be addressed if VSCE supports them.

2025-02-13 15:04 UTC, dcbartlett approved these changes

2025-02-21 17:07 UTC, Tyriar commented
FYI after https://github.com/microsoft/vscode/pull/241491/, `read` should consistently include `633;C` (or `133;C` which is also possible) as the start of the data and consistently _exclude_ `633;D` (or `133;D`).

2025-02-24 21:40 UTC, KJ7LNW commented
> FYI after https://github.com/microsoft/vscode/pull/241491, read should consistently include 633;C (or 133;C which is also possible) as the start of the data and consistently exclude 633;D (or 133;D).

@Tyriar - thank you for pushing that out. Question: under what conditions might `133;[CD]` show up?

(FYI all: I have converted this PR to draft for the moment until we work out 133)

2025-02-25 13:10 UTC, Tyriar commented
@KJ7LNW `133` shows up when it's using the more standard shell integration, not the VS Code-specific scripts. For example the powerlevel10k theme for zsh emits these and disables our shell integration as they wanted full control. It should work exactly the same though so if you need to check this just making sure 133 and 633 are both checked. Note that also in some cases both could be emitted.

It's best generally to avoid looking for these at all and instead filter out all the OSC sequences you don't understand as VS Code will handles them (not consistently).

2025-02-25 20:51 UTC, KJ7LNW commented
> 133 shows up when it's using the more standard shell integration, not the VS Code-specific scripts. For example the powerlevel10k theme for zsh emits these and disables our shell integration as they wanted full control. It should work exactly the same though so if you need to check this just making sure 133 and 633 are both checked. Note that also in some cases both could be emitted.

Okay thanks.

2025-02-27 01:55 UTC, KJ7LNW commented
- rebased on origin/main
- added 633 vs 133 support
- tested bash and zsh w/ powerlevel10k

I think this is ready for use.

2025-03-02 01:04 UTC, pashpashpash requested changes
<img width="384" alt="Screenshot 2025-03-01 at 5 03 12 PM" src="https://github.com/user-attachments/assets/8ac837f1-fe0d-46bb-a215-d53196255c0b" />
Hey guys, I personally would love more reliable consistent shell readability in Cline. Thanks for looking into this.

So I tried out this branch, and my simple test of "please run git status" -- still fails. 

Any idea why?

2025-03-02 23:01 UTC, KJ7LNW commented
Try several times, does it ever work?

2025-03-02 23:02 UTC, KJ7LNW commented
Tell cline:

> run `echo a` and when I reply, run it again.  Stop if you do not recieve "a" from the prompt.

2025-03-02 23:09 UTC, KJ7LNW commented
ok I've reproduced the problem, will look into it...

2025-03-02 23:21 UTC, KJ7LNW commented
@pashpashpash,

I was in the wrong branch, so have NOT reproduced your issue yet.  I've tried the following prompts and can't get it to fail:

run `echo a` and when I reply, run it again. Stop if you do not recieve "a" from the prompt.

2025-03-03 03:59 UTC, KJ7LNW commented
sometimes when running a terminal command, we we receive undefined exit code :

```
[execute_command for 'git status'] Result:

Command executed. Exit code: undefined
```

debug console shows:

```
[TerminalManager] Shell execution ended: {}
```

If you can reproduce this, please tell me how so we can solve it...but I'm concerned its a VSCE bug not a cline bug because `Shell execution ended: {}` happens on `onDidEndTerminalShellExecution` ...

2025-03-03 14:29 UTC, buger commented
@pashpashpash @KJ7LNW this code is quite complex, and to be frank I personally afraid to touch it without proper test coverage. So I have createad this PR, just to add tests https://github.com/cline/cline/pull/2070. 
When it get merged, we can cover all in this PR with tests, and add all the various edge case tests.

2025-03-05 03:59 UTC, KJ7LNW commented
The original upstream vscode bug may not be completely solved. See my new comment here:

https://github.com/microsoft/vscode/issues/237208

2025-03-07 01:52 UTC, KJ7LNW commented
New tests:

- Tests large output processing with 1,000,000 lines of output, ~200ms
- Tests basic command execution with 'echo' commands to verify output handling
- Tests terminal shell execution event handling
- Adds exit code interpretation tests for various scenarios:
  - Normal exit codes (0, 1, 2)
  - Signal termination (SIGTERM, SIGSEGV)
  - Command not found errors

```sh
]$ npx jest ./src/integrations/terminal/__tests__/TerminalProcessExec.test.ts
...
  console.log
    'base64 < /dev/zero | head -n 1000000' execution time: 203925 microseconds (203.925 milliseconds)

      at Object.<anonymous> (src/integrations/terminal/__tests__/TerminalProcessExec.test.ts:374:11)

  console.log
    Output sample (first 3 lines):
     AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    ... (truncated 999995 lines) ...
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

2025-03-07 01:57 UTC, KJ7LNW commented
I see that jest is not available in the testing environment, so I am not sure if you want to keep the test or not. I tried to make it run in the existing framework by just could not get it working without jest. /shrug

2025-03-07 02:55 UTC, buger commented
@KJ7LNW have you saw test suite added in https://github.com/cline/cline/pull/2070 and now in master?

2025-03-07 03:19 UTC, KJ7LNW commented
> @KJ7LNW have you saw test suite added in #2070 and now in master?

I did see that it was added, however there are a few things that I wanted to test separately:

1. actual command execution via exec with output handling 
2. exit code testing
3. signal termination handling
4. complete simulation of onDidStartTerminalShellExecution and onDidEndTerminalShellExecution all the way down to `TerminalProcess.run()`

The test was actually written for Roo, but I thought it might benefit Cline as well, because it has the same issues resolved within Roo's 1365 work in progress:

- [PR \#1365 refactor terminal architecture to address critical issues with the current design](https://github.com/RooVetGit/Roo-Code/pull/1365)

2025-03-25 04:38 UTC, closed without merging