Bugfix/context menu cant find files 374
cline/cline pull request #873
Opened 2024-12-09 08:55 UTC by raceneader

2024-12-26 00:52 UTC, saoudrizwan commented
Thank you for putting this together @raceneader and gah all those screenshots, love to see it! 🙏 This PR touches a lot, but I like the direction of putting more advanced options in vscode settings, perhaps we link out to that from the original settings view? I'll think through this and come back to update your branch and get it merged in.

2024-12-30 18:46 UTC, raceneader commented
Sure thing @saoudrizwan ! I thought I was tackling a small intro issue, but it was bigger than I expected.

The link to vscode settings sounds like a good idea to me.

2025-01-05 03:42 UTC, raceneader commented
@saoudrizwan Give me your thoughts - this a pull request against this pull request.  I couldn't get a direct link to work to get to all Cline settings, but this command path seemed to do the trick.
https://github.com/raceneader/cline/pull/1

2025-02-05 08:28 UTC, NightTrek commented
Hey this looks great im approving it. We have somone working on a PR that this directly effects so im going to have him review it and make the final decision

2025-02-05 08:28 UTC, NightTrek submitted a review, later dismissed

2025-02-05 09:06 UTC, raceneader commented
Thanks @NightTrek, nice to see this getting picked up!  

It's not super obvious from the comments above, but I have another PR waiting in the wings (on my personal branch) that depends on this one. Once this is in, I'll spin that PR up. 

https://github.com/raceneader/cline/pull/1

2025-02-05 15:53 UTC, celestial-vault commented
Heya @raceneader, taking up the torch here.

Can we keep these changes to single PR, single concern? There's a lot being added here, how's about only fixing the "@" mentions for now without the ignoring mechanism? As mentioned above, there is some code coming soon that addresses ignoring files. 

The "flood" protection is a nice-to-have, but I think it too would best be opened in a separate PR.

2025-02-05 15:53 UTC, celestial-vault commented
Regarding [your other PR](https://github.com/raceneader/cline/pull/1), I believe this has already been implemented with the "Advanced Settings" button on Cline's settings tab.

2025-02-05 15:58 UTC, celestial-vault requested changes
Let's only implement the '@' file tagging fix for this PR.

Also, please leave any explanatory comments already existing in the code, unless they are referencing code that is being deleted.

2025-02-05 19:33 UTC, raceneader commented
Great, I see that advanced settings tab is opening the extension configs.

To recap it sounds like we want to restore the hardcoded "dirsToIgnore" variable and the original .gitignore handling (read at extension launch only, no updating) restored to its original state in this PR.  I can also restore the hardcoded 1000 context file limit.

I will restore this comment, which perhaps still has some future value:

```
		/*
		 An event that is emitted when a workspace folder is added or removed.
		 **Note:** this event will not fire if the first workspace folder is added, removed or changed,
		 because in that case the currently executing extensions (including the one that listens to this
		 event) will be terminated and restarted so that the (deprecated) `rootPath` property is updated
		 to point to the first workspace folder.
		 */
		// In other words, we don't have to worry about the root workspace folder ([0]) changing since the extension will be restarted and our cwd will be updated to reflect the new workspace folder. (We don't care about non root workspace folders, since cline will only be working within the root folder cwd)
		// this.disposables.push(vscode.workspace.onDidChangeWorkspaceFolders(this.onWorkspaceFoldersChanged.bind(this)))
```

I wouldn’t recommend decoupling flood protection—it’s a small piece of code that neatly ties this package together. Even relatively minor operations, like moving a medium-sized folder (~100 files), can introduce inconsistencies because not all inotify events reach the handlers, leading to a desynchronized state with the filesystem. Larger operations can further exacerbate the issue by increasing CPU load and degrading application performance.  The workaround for this is to restart the extension, but that was the work-around for the original problem too.

2025-02-07 17:43 UTC, celestial-vault commented
@raceneader Checking in on this

2025-02-07 23:37 UTC, raceneader commented
Hi @celestial-vault, 

I found a corner case that isn’t handled well. Both the original code and the new code (after this PR) fail to respect nested .gitignore files when processing file creations and modifications. This is an issue for the new code because build processes can generate a large number of files that are ignored by nested .gitignore rules, yet these files still make it into the context. The old code doesn’t have this problem because it only sees files created or modified via the VS Code file view, which excludes externally generated files.

If this problem needs to be addressed, I'll add some logic to handle nested .gitignores.

2025-02-08 01:03 UTC, raceneader commented
I got the fix to the nested .gitignore in another branch, ready for PR, once this one is OK:

https://github.com/raceneader/cline/compare/bugfix/context-menu-cant-find-files-374...raceneader:cline:bugfix/nested-gitignore-handling?expand=1

2025-02-08 20:25 UTC, raceneader commented on src/services/glob/list-files.ts
> +export async function listFiles(dirPath: string, recursive: boolean, limit: number): Promise<[string[], boolean]> {
none of this changed, it's just how the diff worked due to moving dirsToIgnore

2025-02-11 02:34 UTC, raceneader commented
> @celestial-vault Seems like @saoudrizwan may have a work-around where changes made by cline are detected and the full file list is updated. Let me know if you want to close this PR, and I will expunge it from my memory. :)

I guess this still might have some value if the user is operating outside cline / vscode... reorganizing paths, generating protobbuf code or migrations, or similar.... ???

2025-02-11 20:42 UTC, celestial-vault commented
@raceneader Hey yes, a pretty simple fix was implemented. Will work on a better alert system for things like this so that community devs can save valuable time in the future.

What do you think can still be used from this PR? If you think it's better closed, that's fine too. Appreciate your efforts on this.

2025-02-11 22:59 UTC, raceneader commented
No worries! I hope I can contribute more useful things in the future.

To answer your question, the PR is stable and usable. IMHO, it seems natural to want to use the file system watcher instead of the workspace watcher... but TBH, 95% of the issue has been addressed by @saoudrizwan fix.

Other than the minor benefits listed in the comment above, the only other thing I can think of is that with large, multi-root repos (one of the contributors was mentioning 40,000 files) the re-indexing / globbing on every change might be sluggish. 

That should be addressed directly by improving globbing performance, but this PR would generally be an efficient  approach for individual file changes (at the cost of code complexity).

2025-02-13 02:09 UTC, closed without merging